// lib/forestOnchain.ts
import type { Abi } from "viem";

// 👉 Replace this with your actual deployed address
export const FOREST_ONCHAIN_ADDRESS =
  "0xB48e40b165A4cC7A54A955888E5232B6c4f05bdb" as const;

// 👉 Paste the ABI generated by Foundry here (from out/ForestOnchain.sol/ForestOnchain.json)
export const FOREST_ONCHAIN_ABI = [
    {
      "type": "constructor",
      "inputs": [
        { "name": "_costPerTree", "type": "uint256", "internalType": "uint256" }
      ],
      "stateMutability": "nonpayable"
    },
    { "type": "fallback", "stateMutability": "payable" },
    { "type": "receive", "stateMutability": "payable" },
    {
      "type": "function",
      "name": "CONTRACT_OWNER",
      "inputs": [],
      "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "changeCostPerTree",
      "inputs": [
        { "name": "_costPerTree", "type": "uint256", "internalType": "uint256" }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "checkActivityExists",
      "inputs": [
        { "name": "_user", "type": "address", "internalType": "address" },
        { "name": "_activityType", "type": "string", "internalType": "string" }
      ],
      "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "checkUpkeep",
      "inputs": [{ "name": "", "type": "bytes", "internalType": "bytes" }],
      "outputs": [
        { "name": "upkeepNeeded", "type": "bool", "internalType": "bool" },
        { "name": "performData", "type": "bytes", "internalType": "bytes" }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "claimStake",
      "inputs": [
        { "name": "_activityType", "type": "string", "internalType": "string" }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "cost_per_tree",
      "inputs": [],
      "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "endFocusSession",
      "inputs": [
        { "name": "_user", "type": "address", "internalType": "address" }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getBreakNeeded",
      "inputs": [
        { "name": "_user", "type": "address", "internalType": "address" }
      ],
      "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getCurrentUserSession",
      "inputs": [
        { "name": "_user", "type": "address", "internalType": "address" }
      ],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct ForestOnchain.UserSession",
          "components": [
            {
              "name": "activityType",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "startTime",
              "type": "uint256",
              "internalType": "uint256"
            },
            { "name": "endTime", "type": "uint256", "internalType": "uint256" },
            { "name": "active", "type": "bool", "internalType": "bool" },
            { "name": "owner", "type": "address", "internalType": "address" }
          ]
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getEndTime",
      "inputs": [
        { "name": "_user", "type": "address", "internalType": "address" },
        { "name": "_activityType", "type": "string", "internalType": "string" }
      ],
      "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getGoal",
      "inputs": [
        { "name": "_user", "type": "address", "internalType": "address" },
        { "name": "_activityType", "type": "string", "internalType": "string" }
      ],
      "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getNumberOfTrees",
      "inputs": [
        { "name": "_user", "type": "address", "internalType": "address" },
        { "name": "_activityType", "type": "string", "internalType": "string" }
      ],
      "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getStakeAmount",
      "inputs": [
        { "name": "_numOfTrees", "type": "uint256", "internalType": "uint256" }
      ],
      "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getStakedAmount",
      "inputs": [
        { "name": "_user", "type": "address", "internalType": "address" },
        { "name": "_activityType", "type": "string", "internalType": "string" }
      ],
      "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getUserActivityTypes",
      "inputs": [
        { "name": "_user", "type": "address", "internalType": "address" }
      ],
      "outputs": [
        { "name": "", "type": "string[]", "internalType": "string[]" }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getUsers",
      "inputs": [],
      "outputs": [
        { "name": "", "type": "address[]", "internalType": "address[]" }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "performUpkeep",
      "inputs": [
        { "name": "performData", "type": "bytes", "internalType": "bytes" }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "startFocusSession",
      "inputs": [
        { "name": "_activityType", "type": "string", "internalType": "string" },
        { "name": "_duration", "type": "uint256", "internalType": "uint256" }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "startGoal",
      "inputs": [
        { "name": "_activityType", "type": "string", "internalType": "string" },
        { "name": "_duration", "type": "uint256", "internalType": "uint256" },
        { "name": "_numOfTrees", "type": "uint256", "internalType": "uint256" }
      ],
      "outputs": [],
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "takeBreak",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "totalStaked",
      "inputs": [],
      "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "withdraw",
      "inputs": [
        { "name": "_to", "type": "address", "internalType": "address payable" },
        { "name": "_amount", "type": "uint256", "internalType": "uint256" }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "ActivityAdded",
      "inputs": [
        {
          "name": "activityType",
          "type": "string",
          "indexed": true,
          "internalType": "string"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "BreakTaken",
      "inputs": [
        {
          "name": "user",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "CostPerTreeChanged",
      "inputs": [
        {
          "name": "costPerTree",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "EtherWithdrawn",
      "inputs": [
        {
          "name": "to",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "GoalClaimed",
      "inputs": [
        {
          "name": "user",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "activityType",
          "type": "string",
          "indexed": true,
          "internalType": "string"
        },
        {
          "name": "stakeAmount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "GoalStarted",
      "inputs": [
        {
          "name": "user",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "activityType",
          "type": "string",
          "indexed": true,
          "internalType": "string"
        },
        {
          "name": "startTime",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "endTime",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "active",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        },
        {
          "name": "numOfTrees",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "stakeAmount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SessionEnded",
      "inputs": [
        {
          "name": "user",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SessionStarted",
      "inputs": [
        {
          "name": "user",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "activityType",
          "type": "string",
          "indexed": true,
          "internalType": "string"
        },
        {
          "name": "startTime",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "endTime",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    { "type": "error", "name": "ForestOnchain__AddActivityType", "inputs": [] },
    {
      "type": "error",
      "name": "ForestOnchain__AnotherSessionOngoing",
      "inputs": [
        { "name": "currentSession", "type": "string", "internalType": "string" }
      ]
    },
    { "type": "error", "name": "ForestOnchain__BreakNeeded", "inputs": [] },
    {
      "type": "error",
      "name": "ForestOnchain__BreakNotNeeded",
      "inputs": [
        { "name": "user", "type": "address", "internalType": "address" }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__CannotSendToZeroAddress",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ForestOnchain__DurationOutOfRange",
      "inputs": [
        { "name": "duration", "type": "uint256", "internalType": "uint256" }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__EnterMoreThankMinNumOfTreesPerGoal",
      "inputs": [
        {
          "name": "numberOfTrees",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__GoalAlreadyExists",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ForestOnchain__GoalDurationIsOver",
      "inputs": [
        { "name": "endTime", "type": "uint256", "internalType": "uint256" },
        { "name": "currentTime", "type": "uint256", "internalType": "uint256" }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__GoalDurationShouldBeMoreThan60Minutes",
      "inputs": [
        { "name": "duration", "type": "uint256", "internalType": "uint256" }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__GoalNotReached",
      "inputs": [
        {
          "name": "numberOfTrees",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__IncorrectStakeSent",
      "inputs": [
        { "name": "sentValue", "type": "uint256", "internalType": "uint256" },
        {
          "name": "requiredStake",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__InsufficientFunds",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ForestOnchain__NoActiveGoal",
      "inputs": [
        { "name": "activityType", "type": "string", "internalType": "string" }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__NoOngoingSession",
      "inputs": [
        { "name": "user", "type": "address", "internalType": "address" }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__SessionNotEndedYet",
      "inputs": [
        {
          "name": "sessionEndTime",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "ForestOnchain__SessionOngoing",
      "inputs": [
        { "name": "user", "type": "address", "internalType": "address" }
      ]
    },
    { "type": "error", "name": "ForestOnchain__TransferFailed", "inputs": [] }
  ] as unknown as Abi;
